### ISSUE TITLE
App is allowing access even if user is not assigned

### ISSUE THREAD

**Issue by Dismissile** [AzureADSamples/WebApp-OpenIDConnect-DotNet#13]
I configured the application following the tutorial and added a new user to the directory. If I go to the Application in the Azure portal and go to the Users section, I see the user I added to the directory and the Assigned status is set to No, but I am still able to sign in with this user and access the application. What is the purpose of the Assigned flag if it does not prevent them from accessing the app?

**Comment by skwan** [comment]
Currently, the assigned flag will put the app onto the user's access panel.  It does not block who can access the application - this is functionality we are working on.

**Comment by Dismissile** [comment]
Hi Stuart. Thanks for responding.
So if I am understanding correctly, right now any authorization rules need to be handled on a per application basis? It cannot be controlled via the directory?

Travis Ellis
Solution Consultant
Office: 402.238.1399 x117
Mobile: 402.415.6398
Deliveron Consulting Services
[cid:image015.png@01CF0620.0729E520]<http://www.deliveron.com/>

[cid:image016.png@01CF0620.0729E520]<https://www.facebook.com/deliveron>

[cid:image017.png@01CF0620.0729E520]<https://twitter.com/deliveron>

[cid:image018.png@01CF0620.0729E520]<http://www.linkedin.com/company/deliveron-consulting-services>

**Comment by skwan** [comment]
That's correct - you must handle authorization in your application right now.
