### ISSUE TITLE
Making this work for microsoft accounts

### ISSUE THREAD

**Issue by gkrilov** [AzureADSamples/WebApp-OpenIDConnect-DotNet#14]
I noticed in the steps you mention that "This sample will not work with a Microsoft account"

Do you know of any way to make the initial login page work for custom domain microsoft accounts such as - something@mydomain.com? One of the option in the azure domain add user is to add an existing microsoft account.. so why dont they provide an easy way to login with such accounts??

Or maybe make it so that instead of the azure AD login page it redirects to the microsoft live login page?

**Comment by skwan** [comment]
We don't support Microsoft accounts in this type of application yet, even if the user is added as Guest in the directory.  Stay tuned, we are working on this capability.
