### ISSUE TITLE
Unneeded reference to ADAL?

### ISSUE THREAD

**Issue by skwan** [AzureADSamples/WebApp-OpenIDConnect-DotNet#16]
After I forked the repro and built it, I got these compiler warnings.  But ADAL is not needed in this project.

1>C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.IdentityModel.Clients.ActiveDirectory". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
1>C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.

**Comment by dstrockis** [comment]
Fixed.
