### ISSUE TITLE
Multiple Reply-Url's

### ISSUE THREAD

**Issue by fujiy** [AzureADSamples/WebApp-OpenIDConnect-DotNet#19]
In development time I want my application posting back to localhost on login, but it just consider the first reply-url configured at my AD App.

Is it expected? There is any workaround?

**Comment by dstrockis** [comment]
You can set the `RedirectUri` parameter to your desired location in `OpenIdConnectAuthenticationOptions`

**Comment by fujiy** [comment]
Worked! Very thanks
