### ISSUE TITLE
Doesn't show the user name

### ISSUE THREAD

**Issue by fujiy** [AzureADSamples/WebApp-OpenIDConnect-DotNet#20]
When I sign in, the header shows: 

Hello live.com#myemail@hotmail.com!

How can I show the real name?

**Comment by dstrockis** [comment]
Hey @fujiy - there's kind of 2 ways to do this.

1) Use `ClaimsPrincipal.Current.Identity.Claims` to directly pull out information from the claims in your controller.

2) In the `OpenIDConnectAuthenticationOptions`, set `TokenValidationParameters` to a new instance of the `TokenValidationParameters` class, and set the `NameClaimType` property to the claim that you want to use as the `User.Identity.Name`

**Comment by fujiy** [comment]
Thanks!

Another question. This values can change? Because I was using TokenValidationParameters like here: https://github.com/AzureADSamples/WebApp-RoleClaims-DotNet/blob/master/WebApp-RoleClaims-DotNet/App_Start/Startup.Auth.cs

But after packages update I needed to change

RoleClaimType = "roles"

To

RoleClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role"

Very thanks

**Comment by dstrockis** [comment]
No, it shouldn't change.  That role claim mapping is a point-in-time fix we had to make.  But generally they should remain constant for you.

**Comment by fujiy** [comment]
I thought it was generated at server-side. Why packages update (client side) made that change?

Anyway, maybe you want to update the samples to use the latest packages.

**Comment by dstrockis** [comment]
Yes, I'll make a note to update.  Client made the change to be compatible with the .NET ClaimTypes.Role enum.

**Comment by fujiy** [comment]
Thanks
