### ISSUE TITLE
First login always fail

### ISSUE THREAD

**Issue by fujiy** [AzureADSamples/WebApp-OpenIDConnect-DotNet#21]
When I login, the  browser stops at https://login.microsoftonline.com/login.srf showing just a #

So when I try again, it doesn't asks for credentials, just posts back and works

**Comment by dstrockis** [comment]
That's weird. Can you provide a Fiddler trace or other trace?  What browser?

**Comment by fujiy** [comment]
I just realized that it also happens when login in to Azure Portal. It should be a Microsoft sign on issue

**Comment by fujiy** [comment]
Doesn't happen with chrome

**Comment by dstrockis** [comment]
If you could post the failing request/response I would be interested in seeing it.

**Comment by fujiy** [comment]
Ok, I'll install fiddler.
I just found a erro on console: Potential cross-site scripting detected in 'https://login.microsoftonline.com/login.srf'. The content has been modified by the XSS Filter.
