### ISSUE TITLE
It it possible to receive Mobile Phone along with the other Claims?

### ISSUE THREAD

**Issue by fujiy** [AzureADSamples/WebApp-OpenIDConnect-DotNet#22]
When you add users in Azure AD you can fill the Work Info, but this information doesn't come along with the other claims.

**Comment by dstrockis** [comment]
No, its not possible today.  The claims docs are here: https://azure.microsoft.com/en-us/documentation/articles/active-directory-token-and-claims/

You can make queries to the Graph API to get this info if you wish.
